/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.DecimalFormat;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import BUS.CTHoaDonBUS;
import DAO.KhachHangDAO;
import DAO.n1_CTHoaDonDAO;
import DAO.n1_HoaDonDAO;
import DAO.n7_KhuyenMaiDAO;
import DAO.n7_UuDaiThanhVienDAO;
import DTO.KhachHangDTO;
import DTO.KhuyenMaiDTO;

/**
 *
 * @author phuoc
 */
public class ChiTietHoaDonGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietHoaDonGUI
     */
    public ChiTietHoaDonGUI(String MHD) {
        setUndecorated(true);
        initComponents(MHD);
        addRowtable(MHD);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String MHD) {

        pnCTHD = new javax.swing.JPanel();
        lbCTHD = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        lbHienThiTenKH = new javax.swing.JLabel();
        jScrollPnCTHD = new javax.swing.JScrollPane();
        tblCTHoaDon = new javax.swing.JTable();
        lbCTKhuyenMai = new javax.swing.JLabel();
        lbHienThiCTKM = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbHienThiTongTien = new javax.swing.JLabel();
        lbCTUuDai = new javax.swing.JLabel();
        lbHienThiCTUD = new javax.swing.JLabel();
        btnTat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnCTHD.setBackground(new java.awt.Color(255, 255, 255));
        pnCTHD.setPreferredSize(new java.awt.Dimension(467, 550));

        lbCTHD.setBackground(new java.awt.Color(255, 255, 255));
        lbCTHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCTHD.setText("Chi tiết hóa đơn");

        lbTenKH.setBackground(new java.awt.Color(255, 255, 255));
        lbTenKH.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbTenKH.setText("Tên khách hàng:");
        if(HDDAO.getHoaDonTheoMHD(MHD).getMaKhachHang()==null)
            lbTenKH.setText("Tên khách hàng:");
        else
            lbTenKH.setText("Tên khách hàng: " + KHDAO.getKhachHangByMaKH(HDDAO.getHoaDonTheoMHD(MHD).getMaKhachHang()).getTenKhachHang());
        lbHienThiTenKH.setBackground(new java.awt.Color(255, 255, 255));
        lbHienThiTenKH.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jScrollPnCTHD.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPnCTHD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPnCTHD.setForeground(new java.awt.Color(255, 255, 255));

        tblCTHoaDon.setBackground(new java.awt.Color(219, 189, 142));
        tblCTHoaDon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblCTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPnCTHD.setViewportView(tblCTHoaDon);
        if (tblCTHoaDon.getColumnModel().getColumnCount() > 0) {
            tblCTHoaDon.getColumnModel().getColumn(0).setResizable(false);
            tblCTHoaDon.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblCTHoaDon.getColumnModel().getColumn(3).setResizable(false);
            tblCTHoaDon.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        lbCTKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbCTKhuyenMai.setText("Chương trình khuyến mãi:");
        if(HDDAO.getHoaDonTheoMHD(MHD).getMaKhuyenMai()==null)
            lbCTKhuyenMai.setText("Chương trình khuyến mãi: ");
        else
            lbCTKhuyenMai.setText("Chương trình khuyến mãi: "+ KMDAO.getKhuyenMaiById(HDDAO.getHoaDonTheoMHD(MHD).getMaKhuyenMai()).getTenKhuyenMai());

        lbHienThiCTKM.setForeground(new java.awt.Color(153, 102, 0));

        lbTongTien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbTongTien.setText("Tổng tiền:");
        String tongTien = String.valueOf(HDDAO.getHoaDonTheoMHD(MHD).getTongTienHoaDon());
        lbTongTien.setText("Tổng tiền: " + formatCurrency(tongTien));
        lbHienThiTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lbHienThiTongTien.setForeground(new java.awt.Color(255, 51, 0));

        lbCTUuDai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbCTUuDai.setText("Chương trình ưu đãi:");
        if(HDDAO.getHoaDonTheoMHD(MHD).getMaUuDai()==null)
            lbCTUuDai.setText("Chương trình ưu đãi:");
        else
            lbCTUuDai.setText("Chương trình ưu đãi: " + UDTVDAO.getUuDaiById(HDDAO.getHoaDonTheoMHD(MHD).getMaUuDai()).getTenUuDai());
        
        lbHienThiCTUD.setForeground(new java.awt.Color(153, 102, 0));

        btnTat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTat.setForeground(new java.awt.Color(255, 51, 0));
        btnTat.setText("X");
        btnTat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCTHDLayout = new javax.swing.GroupLayout(pnCTHD);
        pnCTHD.setLayout(pnCTHDLayout);
        pnCTHDLayout.setHorizontalGroup(
            pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPnCTHD, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(pnCTHDLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCTHDLayout.createSequentialGroup()
                        .addComponent(lbTenKH)
                        .addGap(68, 68, 68)
                        .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCTHDLayout.createSequentialGroup()
                                .addComponent(lbCTHD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnCTHDLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lbHienThiTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCTHDLayout.createSequentialGroup()
                        .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCTKhuyenMai)
                            .addComponent(lbCTUuDai)
                            .addComponent(lbTongTien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnCTHDLayout.createSequentialGroup()
                                .addComponent(lbHienThiCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(pnCTHDLayout.createSequentialGroup()
                                .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHienThiTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbHienThiCTUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        pnCTHDLayout.setVerticalGroup(
            pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCTHDLayout.createSequentialGroup()
                .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCTHDLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbCTHD))
                    .addComponent(btnTat))
                .addGap(40, 40, 40)
                .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnCTHDLayout.createSequentialGroup()
                        .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHienThiTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenKH))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPnCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbHienThiCTKM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbCTKhuyenMai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHienThiCTUD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCTUuDai, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHienThiTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCTHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCTHD, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnTatActionPerformed

    public void addRowtable(String MHD) {
        CTHDBUS.HienThiChiTietHoaDon( tblCTHoaDon, MHD );

    }

    public String formatCurrency(String amountStr) {
        try {
            double amount = Double.parseDouble(amountStr);
            DecimalFormat formatter = new DecimalFormat("#,###");
            String formatted = formatter.format(amount);
            return formatted + " VNĐ";
        } catch (NumberFormatException e) {
            return "Số không hợp lệ";
        }
    }

    /**
     * @param args the command line arguments
     */
   
    //Khai báo các đối tượng cần dùng
    private KhachHangDAO KHDAO = new KhachHangDAO();
    private KhachHangDTO KHDTO = new KhachHangDTO();
    private KhuyenMaiDTO KMDTO = new KhuyenMaiDTO();
    private n7_KhuyenMaiDAO KMDAO = new n7_KhuyenMaiDAO();
    private n1_HoaDonDAO HDDAO  = new n1_HoaDonDAO();
    private CTHoaDonBUS CTHDBUS = new CTHoaDonBUS();
    private n7_UuDaiThanhVienDAO UDTVDAO = new n7_UuDaiThanhVienDAO();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTat;
    private javax.swing.JScrollPane jScrollPnCTHD;
    private javax.swing.JLabel lbCTHD;
    private javax.swing.JLabel lbCTKhuyenMai;
    private javax.swing.JLabel lbCTUuDai;
    private javax.swing.JLabel lbHienThiCTKM;
    private javax.swing.JLabel lbHienThiCTUD;
    private javax.swing.JLabel lbHienThiTenKH;
    private javax.swing.JLabel lbHienThiTongTien;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JPanel pnCTHD;
    private javax.swing.JTable tblCTHoaDon;
    // End of variables declaration//GEN-END:variables
}
