/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import BUS.NhanVienBUS;
import BUS.PhanQuyenBUS;
import BUS.TaiKhoanBUS;
import DTO.NhanVienDTO;
import DTO.PhanQuyenDTO;
import Util.dialog;

/**
 *
 * @author phuoc
 */
public class dlgInforAcc_QuyenNV extends javax.swing.JPanel {
    private String maNV;
    private PhanQuyenBUS PQBUS = new PhanQuyenBUS();
    private NhanVienBUS NVBUS = new NhanVienBUS();
    private TaiKhoanBUS TKBUS = new TaiKhoanBUS();
    /**
     * Creates new form dlgInforAcc_QuyenNV
     */
    public dlgInforAcc_QuyenNV(String maNV) {
        this.maNV = maNV;
        initComponents();
    }

    public boolean loadData() {
        txtMaNhanVien.setText(maNV);
        jTextFieldMaNV.setText(maNV);
        String tenDangNhap = TKBUS.getTenDangNhapTheoMa(maNV);
        if (tenDangNhap.equals("")) {
            new dialog("Nhân viên này chưa có tài khoản!", dialog.ERROR_DIALOG);
            return false;
        }
        txtTenDN.setText(tenDangNhap);//
        txtMatKhauTTTK.setText(TKBUS.getMatKhauByMaNV(maNV));//lấy mật khẩu từ truy vấn từ mã nhân viên trong tài khoản lên

        BoxQuyen.removeAllItems();
        ArrayList<PhanQuyenDTO> dsq = PQBUS.getList();
        for (PhanQuyenDTO pq : dsq) {
            BoxQuyen.addItem(pq.getTenQuyen());
        }

        String maQuyen = TKBUS.getQuyenTheoMa(maNV); 
        // lấy mã quyền
        PhanQuyenDTO currentQuyen = PQBUS.getById(maQuyen); // lấy quyền
        if (currentQuyen == null) {
            return false;
        }
        for (int i = 0; i < BoxQuyen.getItemCount(); i++) {
            if ((BoxQuyen.getItemAt(i) + "").equals(currentQuyen.getTenQuyen())) {
                BoxQuyen.setSelectedIndex(i);
                break;
            }
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnInforNV_Q = new javax.swing.JPanel();
        PnThongTinTk_Quyen = new javax.swing.JTabbedPane();
        jPanelThongTinTK = new javax.swing.JPanel();
        pnThongTinTK = new javax.swing.JLabel();
        jLbMaNV = new javax.swing.JLabel();
        jLabelTenDN = new javax.swing.JLabel();
        jLabelMK = new javax.swing.JLabel();
        jTextFieldMaNV = new javax.swing.JTextField();
        txtTenDN = new javax.swing.JTextField();
        txtMatKhauTTTK = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanelThongTinQuyen = new javax.swing.JPanel();
        jLabelThongTinQuyen = new javax.swing.JLabel();
        lbMaNhanVien = new javax.swing.JLabel();
        lbQuyenTK = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnXacNhanThayDoiQuyen = new javax.swing.JPanel();
        LBXacNhanThayDoiQuyen = new javax.swing.JLabel();
        BoxQuyen = new javax.swing.JComboBox<>();
        pnDoiMK = new javax.swing.JPanel();
        lb_thayDoiMatKhau = new javax.swing.JLabel();
        lbMkHienTai = new javax.swing.JLabel();
        txtMatKhauHT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbMatKhauMoi = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lbNhapLaiMatKhauMoi = new javax.swing.JLabel();
        txtNhapLaiMatKhauMoi = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnXacNhanDoiMatKhau = new javax.swing.JLabel();

        pnInforNV_Q.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PnThongTinTk_Quyen.setBackground(new java.awt.Color(219, 189, 142));
        PnThongTinTk_Quyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelThongTinTK.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThongTinTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnThongTinTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnThongTinTK.setText("Thông tin tài khoản");

        jLbMaNV.setText("Mã Nhân viên");

        jLabelTenDN.setText("Tên đăng nhập");

        jLabelMK.setText("Mật khẩu");

        jTextFieldMaNV.setEditable(false);
        jTextFieldMaNV.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMaNV.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtTenDN.setEditable(false);
        txtTenDN.setBackground(new java.awt.Color(255, 255, 255));
        txtTenDN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtTenDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDNActionPerformed(evt);
            }
        });

        txtMatKhauTTTK.setEditable(false);
        txtMatKhauTTTK.setBackground(new java.awt.Color(255, 255, 255));
        txtMatKhauTTTK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanelThongTinTKLayout = new javax.swing.GroupLayout(jPanelThongTinTK);
        jPanelThongTinTK.setLayout(jPanelThongTinTKLayout);
        jPanelThongTinTKLayout.setHorizontalGroup(
            jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinTKLayout.createSequentialGroup()
                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinTKLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(pnThongTinTK))
                    .addGroup(jPanelThongTinTKLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelThongTinTKLayout.createSequentialGroup()
                                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTenDN)
                                    .addComponent(jLabelMK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelThongTinTKLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMatKhauTTTK, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinTKLayout.createSequentialGroup()
                                .addComponent(jLbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanelThongTinTKLayout.setVerticalGroup(
            jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThongTinTK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatKhauTTTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        PnThongTinTk_Quyen.addTab("Thông tin tài khoản", jPanelThongTinTK);

        jPanelThongTinQuyen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelThongTinQuyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelThongTinQuyen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelThongTinQuyen.setText("Thông tin quyền");

        lbMaNhanVien.setText("Mã Nhân viên");

        lbQuyenTK.setText("Quyền tài khoản");

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnXacNhanThayDoiQuyen.setBackground(new java.awt.Color(219, 189, 142));
        btnXacNhanThayDoiQuyen.setMaximumSize(new java.awt.Dimension(114, 39));
        btnXacNhanThayDoiQuyen.setMinimumSize(new java.awt.Dimension(114, 39));
        btnXacNhanThayDoiQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanThayDoiQuyenMouseClicked(evt);
            }
        });

        LBXacNhanThayDoiQuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBXacNhanThayDoiQuyen.setText("Xác nhận thay đổi");

        javax.swing.GroupLayout btnXacNhanThayDoiQuyenLayout = new javax.swing.GroupLayout(btnXacNhanThayDoiQuyen);
        btnXacNhanThayDoiQuyen.setLayout(btnXacNhanThayDoiQuyenLayout);
        btnXacNhanThayDoiQuyenLayout.setHorizontalGroup(
            btnXacNhanThayDoiQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnXacNhanThayDoiQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBXacNhanThayDoiQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );
        btnXacNhanThayDoiQuyenLayout.setVerticalGroup(
            btnXacNhanThayDoiQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnXacNhanThayDoiQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBXacNhanThayDoiQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        BoxQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelThongTinQuyenLayout = new javax.swing.GroupLayout(jPanelThongTinQuyen);
        jPanelThongTinQuyen.setLayout(jPanelThongTinQuyenLayout);
        jPanelThongTinQuyenLayout.setHorizontalGroup(
            jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinQuyenLayout.createSequentialGroup()
                .addGroup(jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinQuyenLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabelThongTinQuyen))
                    .addGroup(jPanelThongTinQuyenLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelThongTinQuyenLayout.createSequentialGroup()
                                .addComponent(lbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BoxQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbQuyenTK)))
                    .addGroup(jPanelThongTinQuyenLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnXacNhanThayDoiQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanelThongTinQuyenLayout.setVerticalGroup(
            jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinQuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThongTinQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanelThongTinQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuyenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnXacNhanThayDoiQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        PnThongTinTk_Quyen.addTab("Thông tin quyền", jPanelThongTinQuyen);

        pnDoiMK.setBackground(new java.awt.Color(255, 255, 255));

        lb_thayDoiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lb_thayDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_thayDoiMatKhau.setText("Thay đổi mật khẩu");

        lbMkHienTai.setText("Nhập mật khẩu hiện tại");

        txtMatKhauHT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbMatKhauMoi.setText("Nhập mật mới");

        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbNhapLaiMatKhauMoi.setText("Nhập lại mật khẩu mới");

        txtNhapLaiMatKhauMoi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel2.setBackground(new java.awt.Color(219, 189, 142));

        btnXacNhanDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXacNhanDoiMatKhau.setText("Xác nhận thay đổi");
        btnXacNhanDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanDoiMatKhauMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXacNhanDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXacNhanDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnDoiMKLayout = new javax.swing.GroupLayout(pnDoiMK);
        pnDoiMK.setLayout(pnDoiMKLayout);
        pnDoiMKLayout.setHorizontalGroup(
            pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoiMKLayout.createSequentialGroup()
                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDoiMKLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lb_thayDoiMatKhau))
                    .addGroup(pnDoiMKLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnDoiMKLayout.createSequentialGroup()
                                .addComponent(lbMatKhauMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatKhauMoi)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnDoiMKLayout.createSequentialGroup()
                                .addComponent(lbMkHienTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatKhauHT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jSeparator2)))
                            .addGroup(pnDoiMKLayout.createSequentialGroup()
                                .addComponent(lbNhapLaiMatKhauMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNhapLaiMatKhauMoi)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnDoiMKLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        pnDoiMKLayout.setVerticalGroup(
            pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDoiMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_thayDoiMatKhau)
                .addGap(31, 31, 31)
                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDoiMKLayout.createSequentialGroup()
                        .addComponent(lbMkHienTai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMatKhauHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDoiMKLayout.createSequentialGroup()
                        .addComponent(lbMatKhauMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDoiMKLayout.createSequentialGroup()
                        .addComponent(lbNhapLaiMatKhauMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        PnThongTinTk_Quyen.addTab("Thay đổi mật khẩu", pnDoiMK);

        javax.swing.GroupLayout pnInforNV_QLayout = new javax.swing.GroupLayout(pnInforNV_Q);
        pnInforNV_Q.setLayout(pnInforNV_QLayout);
        pnInforNV_QLayout.setHorizontalGroup(
            pnInforNV_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnThongTinTk_Quyen)
        );
        pnInforNV_QLayout.setVerticalGroup(
            pnInforNV_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnThongTinTk_Quyen, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnInforNV_Q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInforNV_Q, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDNActionPerformed
        
        // dispose();
    }//GEN-LAST:event_txtTenDNActionPerformed

    private void btnXacNhanThayDoiQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanThayDoiQuyenMouseClicked
        if(BoxQuyen.getSelectedItem().equals("Quản Trị Viên")){
            JOptionPane.showMessageDialog(null, "Đã tồn tại Quản trị viên,\n Không thể thêm quản trị viên thứ 2!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return ;            
        }        
        TKBUS.datLaiQuyen(maNV, PQBUS.layMaTheoTenQuyen(BoxQuyen.getSelectedItem() + ""));
        // sửa lại thành lấy mã nhân viên
        NVBUS.CapNhatChucVu(new NhanVienDTO(maNV, null, null, null, null, BoxQuyen.getSelectedItem() + "",null,0, 1));
    }//GEN-LAST:event_btnXacNhanThayDoiQuyenMouseClicked

    private void btnXacNhanDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanDoiMatKhauMouseClicked
        String mk = TKBUS.getMatKhauByMaNV(maNV);
        String mkCu = txtMatKhauHT.getText().trim();
        String mkMoi = txtMatKhauMoi.getText().trim();
        String nhapLaiMkMoi = txtNhapLaiMatKhauMoi.getText().trim();

        int maxlenght = 50;
        int minLenght = 6;
        String regex = "^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>/?]*$";
        if(mkCu.equals(""))
            new dialog("Không được để trống mặt khẩu hiện tại", dialog.ERROR_DIALOG);

        else if(!mkCu.equals(mk))
            new dialog("Mật khẩu hiện tại sai", dialog.ERROR_DIALOG);
        
        else if(mkMoi.equals(mk))
            new dialog("Mật khẩu mới trùng với mật khẩu hiện tại", dialog.ERROR_DIALOG);

        else if(mkMoi.equals(""))
            new dialog("Không được để trống mặt khẩu mới", dialog.ERROR_DIALOG);

        else if(mkMoi.contains(" "))
            new dialog("Không được có khoảng cách trong mật khẩu mới", dialog.ERROR_DIALOG);

        else if(mkMoi.length() > maxlenght)
            new dialog("Mật khẩu mới không được quá 50 ký tự", dialog.ERROR_DIALOG);

        else if(mkMoi.length() < minLenght)
            new dialog("Mật khẩu mới không được ít hơn 6 ký tự", dialog.ERROR_DIALOG);

        else if(!mkMoi.matches(regex))
            new dialog("Mật khẩu mới không được có dấu", dialog.ERROR_DIALOG);

        else if(nhapLaiMkMoi.equals(""))
            new dialog("Mật khẩu nhập lại không được để trống", dialog.ERROR_DIALOG);

        else if(!nhapLaiMkMoi.equals(mkMoi))
            new dialog("Mật khẩu mới nhập lại không khớp", dialog.ERROR_DIALOG);

        else{
            boolean check = TKBUS.doiMatKhau(mkMoi, mkCu, maNV);
            if(check){
                txtMatKhauHT.setText("");
                txtMatKhauMoi.setText("");
                txtNhapLaiMatKhauMoi.setText("");
            }

        }
    }//GEN-LAST:event_btnXacNhanDoiMatKhauMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxQuyen;
    private javax.swing.JLabel LBXacNhanThayDoiQuyen;
    private javax.swing.JTabbedPane PnThongTinTk_Quyen;
    private javax.swing.JLabel btnXacNhanDoiMatKhau;
    private javax.swing.JPanel btnXacNhanThayDoiQuyen;
    private javax.swing.JLabel jLabelMK;
    private javax.swing.JLabel jLabelTenDN;
    private javax.swing.JLabel jLabelThongTinQuyen;
    private javax.swing.JLabel jLbMaNV;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelThongTinQuyen;
    private javax.swing.JPanel jPanelThongTinTK;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldMaNV;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JLabel lbMatKhauMoi;
    private javax.swing.JLabel lbMkHienTai;
    private javax.swing.JLabel lbNhapLaiMatKhauMoi;
    private javax.swing.JLabel lbQuyenTK;
    private javax.swing.JLabel lb_thayDoiMatKhau;
    private javax.swing.JPanel pnDoiMK;
    private javax.swing.JPanel pnInforNV_Q;
    private javax.swing.JLabel pnThongTinTK;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhauHT;
    private javax.swing.JTextField txtMatKhauMoi;
    private javax.swing.JTextField txtMatKhauTTTK;
    private javax.swing.JTextField txtNhapLaiMatKhauMoi;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
