/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author as
 */
public class n3_PNThongTinPhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form PNThongTinHoaDon
     */
    public n3_PNThongTinPhieuNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_NoiDungTTPN = new javax.swing.JPanel();
        jL_ThongTinPhieuNhap = new javax.swing.JLabel();
        jP_ThongTinPhieuNhap = new javax.swing.JPanel();
        jP_NhanVien = new javax.swing.JPanel();
        jL_NhanVien = new javax.swing.JLabel();
        jT_NhanVien = new javax.swing.JTextField();
        jP_Ncc = new javax.swing.JPanel();
        jL_Ncc = new javax.swing.JLabel();
        jT_Ncc = new javax.swing.JTextField();
        jP_TongTien = new javax.swing.JPanel();
        jL_TongTien = new javax.swing.JLabel();
        jT_TongTien = new javax.swing.JTextField();
        jP_NgayLap = new javax.swing.JPanel();
        jL_NgayLap = new javax.swing.JLabel();
        jT_NgayLap = new javax.swing.JTextField();
        jL_ChiTietPhieuNhap = new javax.swing.JLabel();
        jP_ChoNhap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ChoNhap = new javax.swing.JTable();
        jBtn_XacNhanNhap = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jP_NoiDungTTPN.setBackground(new java.awt.Color(219, 189, 142));
        jP_NoiDungTTPN.setMaximumSize(new java.awt.Dimension(550, 600));
        jP_NoiDungTTPN.setMinimumSize(new java.awt.Dimension(550, 600));
        jP_NoiDungTTPN.setPreferredSize(new java.awt.Dimension(550, 600));

        jL_ThongTinPhieuNhap.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jL_ThongTinPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ThongTinPhieuNhap.setText("Thông Tin Phiếu Nhập");

        jP_ThongTinPhieuNhap.setBackground(new java.awt.Color(255, 255, 255));
        jP_ThongTinPhieuNhap.setMaximumSize(new java.awt.Dimension(540, 260));
        jP_ThongTinPhieuNhap.setMinimumSize(new java.awt.Dimension(540, 260));
        jP_ThongTinPhieuNhap.setPreferredSize(new java.awt.Dimension(540, 260));

        jP_NhanVien.setBackground(new java.awt.Color(255, 255, 255));
        jP_NhanVien.setMaximumSize(new java.awt.Dimension(510, 30));
        jP_NhanVien.setMinimumSize(new java.awt.Dimension(510, 30));
        jP_NhanVien.setPreferredSize(new java.awt.Dimension(510, 30));

        jL_NhanVien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jL_NhanVien.setText("Nhân Viên:");
        jL_NhanVien.setMaximumSize(new java.awt.Dimension(100, 30));
        jL_NhanVien.setMinimumSize(new java.awt.Dimension(100, 30));
        jL_NhanVien.setPreferredSize(new java.awt.Dimension(100, 30));

        jT_NhanVien.setBackground(new java.awt.Color(245, 245, 245));
        jT_NhanVien.setMaximumSize(new java.awt.Dimension(375, 30));
        jT_NhanVien.setMinimumSize(new java.awt.Dimension(375, 30));
        jT_NhanVien.setPreferredSize(new java.awt.Dimension(375, 30));

        javax.swing.GroupLayout jP_NhanVienLayout = new javax.swing.GroupLayout(jP_NhanVien);
        jP_NhanVien.setLayout(jP_NhanVienLayout);
        jP_NhanVienLayout.setHorizontalGroup(
            jP_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NhanVienLayout.createSequentialGroup()
                .addComponent(jL_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jT_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_NhanVienLayout.setVerticalGroup(
            jP_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jT_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jP_Ncc.setBackground(new java.awt.Color(255, 255, 255));
        jP_Ncc.setMaximumSize(new java.awt.Dimension(510, 30));
        jP_Ncc.setMinimumSize(new java.awt.Dimension(510, 30));
        jP_Ncc.setPreferredSize(new java.awt.Dimension(510, 30));

        jL_Ncc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jL_Ncc.setText("Nhà Cung Cấp:");
        jL_Ncc.setMaximumSize(new java.awt.Dimension(100, 30));
        jL_Ncc.setMinimumSize(new java.awt.Dimension(100, 30));
        jL_Ncc.setPreferredSize(new java.awt.Dimension(100, 30));

        jT_Ncc.setBackground(new java.awt.Color(245, 245, 245));
        jT_Ncc.setMaximumSize(new java.awt.Dimension(375, 30));
        jT_Ncc.setMinimumSize(new java.awt.Dimension(375, 30));
        jT_Ncc.setPreferredSize(new java.awt.Dimension(375, 30));

        javax.swing.GroupLayout jP_NccLayout = new javax.swing.GroupLayout(jP_Ncc);
        jP_Ncc.setLayout(jP_NccLayout);
        jP_NccLayout.setHorizontalGroup(
            jP_NccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NccLayout.createSequentialGroup()
                .addComponent(jL_Ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jT_Ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_NccLayout.setVerticalGroup(
            jP_NccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_Ncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jT_Ncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jP_TongTien.setBackground(new java.awt.Color(255, 255, 255));
        jP_TongTien.setMaximumSize(new java.awt.Dimension(510, 30));
        jP_TongTien.setMinimumSize(new java.awt.Dimension(510, 30));
        jP_TongTien.setPreferredSize(new java.awt.Dimension(510, 30));

        jL_TongTien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jL_TongTien.setText("Tổng Tiền:");
        jL_TongTien.setMaximumSize(new java.awt.Dimension(100, 30));
        jL_TongTien.setMinimumSize(new java.awt.Dimension(100, 30));
        jL_TongTien.setPreferredSize(new java.awt.Dimension(100, 30));

        jT_TongTien.setBackground(new java.awt.Color(245, 245, 245));
        jT_TongTien.setMaximumSize(new java.awt.Dimension(375, 30));
        jT_TongTien.setMinimumSize(new java.awt.Dimension(375, 30));
        jT_TongTien.setPreferredSize(new java.awt.Dimension(375, 30));
        jT_TongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TongTienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_TongTienLayout = new javax.swing.GroupLayout(jP_TongTien);
        jP_TongTien.setLayout(jP_TongTienLayout);
        jP_TongTienLayout.setHorizontalGroup(
            jP_TongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TongTienLayout.createSequentialGroup()
                .addComponent(jL_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jT_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_TongTienLayout.setVerticalGroup(
            jP_TongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jT_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jP_NgayLap.setBackground(new java.awt.Color(255, 255, 255));
        jP_NgayLap.setMaximumSize(new java.awt.Dimension(510, 30));
        jP_NgayLap.setMinimumSize(new java.awt.Dimension(510, 30));
        jP_NgayLap.setPreferredSize(new java.awt.Dimension(510, 30));

        jL_NgayLap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jL_NgayLap.setText("Ngày Lập:");

        jT_NgayLap.setBackground(new java.awt.Color(245, 245, 245));
        jT_NgayLap.setMaximumSize(new java.awt.Dimension(375, 30));
        jT_NgayLap.setMinimumSize(new java.awt.Dimension(375, 30));
        jT_NgayLap.setPreferredSize(new java.awt.Dimension(375, 30));
        jT_NgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NgayLapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_NgayLapLayout = new javax.swing.GroupLayout(jP_NgayLap);
        jP_NgayLap.setLayout(jP_NgayLapLayout);
        jP_NgayLapLayout.setHorizontalGroup(
            jP_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NgayLapLayout.createSequentialGroup()
                .addComponent(jL_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jT_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_NgayLapLayout.setVerticalGroup(
            jP_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_NgayLapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jT_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jP_ThongTinPhieuNhapLayout = new javax.swing.GroupLayout(jP_ThongTinPhieuNhap);
        jP_ThongTinPhieuNhap.setLayout(jP_ThongTinPhieuNhapLayout);
        jP_ThongTinPhieuNhapLayout.setHorizontalGroup(
            jP_ThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ThongTinPhieuNhapLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jP_ThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_Ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jP_ThongTinPhieuNhapLayout.setVerticalGroup(
            jP_ThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ThongTinPhieuNhapLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jP_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jP_Ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jL_ChiTietPhieuNhap.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jL_ChiTietPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ChiTietPhieuNhap.setText("Chi Tiết Phiếu Nhập");

        jP_ChoNhap.setPreferredSize(new java.awt.Dimension(535, 230));

        jTable_ChoNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã PN", "Tên SP", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jTable_ChoNhap.setMaximumSize(new java.awt.Dimension(635, 215));
        jTable_ChoNhap.setMinimumSize(new java.awt.Dimension(635, 215));
        jScrollPane2.setViewportView(jTable_ChoNhap);

        javax.swing.GroupLayout jP_ChoNhapLayout = new javax.swing.GroupLayout(jP_ChoNhap);
        jP_ChoNhap.setLayout(jP_ChoNhapLayout);
        jP_ChoNhapLayout.setHorizontalGroup(
            jP_ChoNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jP_ChoNhapLayout.setVerticalGroup(
            jP_ChoNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        jBtn_XacNhanNhap.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_XacNhanNhap.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_XacNhanNhap.setText("Xác Nhận Nhập");
        jBtn_XacNhanNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_XacNhanNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_NoiDungTTPNLayout = new javax.swing.GroupLayout(jP_NoiDungTTPN);
        jP_NoiDungTTPN.setLayout(jP_NoiDungTTPNLayout);
        jP_NoiDungTTPNLayout.setHorizontalGroup(
            jP_NoiDungTTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NoiDungTTPNLayout.createSequentialGroup()
                .addGroup(jP_NoiDungTTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_NoiDungTTPNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_ChiTietPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jP_NoiDungTTPNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jP_NoiDungTTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_ThongTinPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_ChoNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                            .addComponent(jP_ThongTinPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_NoiDungTTPNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtn_XacNhanNhap)
                .addGap(241, 241, 241))
        );
        jP_NoiDungTTPNLayout.setVerticalGroup(
            jP_NoiDungTTPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_NoiDungTTPNLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jL_ThongTinPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_ThongTinPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jL_ChiTietPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_ChoNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_XacNhanNhap)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_NoiDungTTPN, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_NoiDungTTPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_NgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NgayLapActionPerformed

    private void jT_TongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_TongTienActionPerformed

    private void jBtn_XacNhanNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_XacNhanNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_XacNhanNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_XacNhanNhap;
    private javax.swing.JLabel jL_ChiTietPhieuNhap;
    private javax.swing.JLabel jL_Ncc;
    private javax.swing.JLabel jL_NgayLap;
    private javax.swing.JLabel jL_NhanVien;
    private javax.swing.JLabel jL_ThongTinPhieuNhap;
    private javax.swing.JLabel jL_TongTien;
    private javax.swing.JPanel jP_ChoNhap;
    private javax.swing.JPanel jP_Ncc;
    private javax.swing.JPanel jP_NgayLap;
    private javax.swing.JPanel jP_NhanVien;
    private javax.swing.JPanel jP_NoiDungTTPN;
    private javax.swing.JPanel jP_ThongTinPhieuNhap;
    private javax.swing.JPanel jP_TongTien;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jT_Ncc;
    private javax.swing.JTextField jT_NgayLap;
    private javax.swing.JTextField jT_NhanVien;
    private javax.swing.JTextField jT_TongTien;
    private javax.swing.JTable jTable_ChoNhap;
    // End of variables declaration//GEN-END:variables
}
