/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author as
 */
public class n3_PNChonNCC extends javax.swing.JPanel {

    /**
     * Creates new form PNChonNCC
     */
    public n3_PNChonNCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_ChonNCC = new javax.swing.JPanel();
        jL_ChonNcc = new javax.swing.JLabel();
        jP_TimKiem = new javax.swing.JPanel();
        jL_TimKiem = new javax.swing.JLabel();
        jT_TimKiem = new javax.swing.JTextField();
        jP_List = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_list = new javax.swing.JTable();
        jP_btn = new javax.swing.JPanel();
        jBtn_Chon = new javax.swing.JButton();
        jBtn_Them = new javax.swing.JButton();
        jBtn_Sua = new javax.swing.JButton();
        jBtn_Xoa = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(500, 450));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));

        jP_ChonNCC.setBackground(new java.awt.Color(219, 189, 142));

        jL_ChonNcc.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jL_ChonNcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ChonNcc.setText("Chọn Nhà Cung Cấp");

        jP_TimKiem.setBackground(new java.awt.Color(219, 189, 142));

        jL_TimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jL_TimKiem.setText("Tìm Kiếm:");

        jT_TimKiem.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jP_TimKiemLayout = new javax.swing.GroupLayout(jP_TimKiem);
        jP_TimKiem.setLayout(jP_TimKiemLayout);
        jP_TimKiemLayout.setHorizontalGroup(
            jP_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TimKiemLayout.createSequentialGroup()
                .addComponent(jL_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jT_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_TimKiemLayout.setVerticalGroup(
            jP_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jL_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jT_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC", "Địa Chỉ", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(jTable_list);

        javax.swing.GroupLayout jP_ListLayout = new javax.swing.GroupLayout(jP_List);
        jP_List.setLayout(jP_ListLayout);
        jP_ListLayout.setHorizontalGroup(
            jP_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jP_ListLayout.setVerticalGroup(
            jP_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jP_btn.setBackground(new java.awt.Color(219, 189, 142));

        jBtn_Chon.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_Chon.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_Chon.setText("Chọn");

        jBtn_Them.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_Them.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_Them.setText("Thêm");

        jBtn_Sua.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_Sua.setText("Sửa");

        jBtn_Xoa.setBackground(new java.awt.Color(0, 0, 0));
        jBtn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_Xoa.setText("Xóa");

        javax.swing.GroupLayout jP_btnLayout = new javax.swing.GroupLayout(jP_btn);
        jP_btn.setLayout(jP_btnLayout);
        jP_btnLayout.setHorizontalGroup(
            jP_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_btnLayout.createSequentialGroup()
                .addComponent(jBtn_Chon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_Xoa)
                .addContainerGap())
        );
        jP_btnLayout.setVerticalGroup(
            jP_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtn_Chon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jBtn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jP_ChonNCCLayout = new javax.swing.GroupLayout(jP_ChonNCC);
        jP_ChonNCC.setLayout(jP_ChonNCCLayout);
        jP_ChonNCCLayout.setHorizontalGroup(
            jP_ChonNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ChonNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ChonNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ChonNCCLayout.createSequentialGroup()
                        .addGroup(jP_ChonNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_ChonNcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ChonNCCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jP_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ChonNCCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jP_ChonNCCLayout.setVerticalGroup(
            jP_ChonNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ChonNCCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_ChonNcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jP_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_ChonNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_ChonNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Chon;
    private javax.swing.JButton jBtn_Sua;
    private javax.swing.JButton jBtn_Them;
    private javax.swing.JButton jBtn_Xoa;
    private javax.swing.JLabel jL_ChonNcc;
    private javax.swing.JLabel jL_TimKiem;
    private javax.swing.JPanel jP_ChonNCC;
    private javax.swing.JPanel jP_List;
    private javax.swing.JPanel jP_TimKiem;
    private javax.swing.JPanel jP_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_TimKiem;
    private javax.swing.JTable jTable_list;
    // End of variables declaration//GEN-END:variables
}
