/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Util.TableCustom;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


import DTO.LoaiMonDTO;
import DTO.MonDTO;
import BUS.n4_LoaiMonBUS;
/**
 *
 * @author dvmv2
 */
public class n4_LoaiMonDialog extends javax.swing.JFrame {
    private n4_LoaiMonBUS loaiMonBUS;
    private String regex = ".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>/?~].*";
    /**
     * Creates new form LoaiMonJFrame
     */
    public n4_LoaiMonDialog() {
        loaiMonBUS = new n4_LoaiMonBUS();
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dsLoaiMon = new javax.swing.JTable();
        lb_TenLoaiMon = new javax.swing.JLabel();
        lb_MaLoaiMon = new javax.swing.JLabel();
        tf_MaLoaiMon = new javax.swing.JTextField();
        tf_TenLoaiMon = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_XuatExcel = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        fillTable();
        tb_dsLoaiMon.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int selectedRow = tb_dsLoaiMon.getSelectedRow();
                    if (selectedRow != -1) {
                        String maLoaiMon = String.valueOf(tb_dsLoaiMon.getValueAt(selectedRow, 0));
                        String tenLoaiMon =  String.valueOf(tb_dsLoaiMon.getValueAt(selectedRow, 1));
                        tf_MaLoaiMon.setText(maLoaiMon);
                        tf_TenLoaiMon.setText(tenLoaiMon);
                    }
                }
            }
        });
        jScrollPane1.setViewportView(tb_dsLoaiMon);

        lb_TenLoaiMon.setText("Tên Loại Món");

        lb_MaLoaiMon.setText("Mã Loại Món");

        tf_MaLoaiMon.setBorder(null);
        tf_MaLoaiMon.setEditable(false);
        tf_MaLoaiMon.setEnabled(false);
        tf_MaLoaiMon.setBackground(Color.WHITE);
        tf_MaLoaiMon.setDisabledTextColor(Color.BLACK);

        tf_TenLoaiMon.setBorder(null);

        btn_Them.setBackground(new java.awt.Color(0, 0, 0));
        btn_Them.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btn_ThemAction();
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(0, 0, 0));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btn_XoaAction();
            }
        });

        btn_XuatExcel.setBackground(new java.awt.Color(0, 0, 0));
        btn_XuatExcel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_XuatExcel.setForeground(new java.awt.Color(255, 255, 255));
        btn_XuatExcel.setText("Xuất Excel");
        btn_XuatExcel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btn_XuatExcelAction();
            }
        });

        btn_Sua.setBackground(new java.awt.Color(0, 0, 0));
        btn_Sua.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btn_SuaAction();
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_TenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_MaLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_MaLoaiMon, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(tf_TenLoaiMon)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XuatExcel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_MaLoaiMon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(tf_MaLoaiMon)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n4_LoaiMonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n4_LoaiMonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n4_LoaiMonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n4_LoaiMonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n4_LoaiMonDialog().setVisible(true);
            }
        });
    }
    public void fillTable() {
        DefaultTableModel modelTable = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                // Không cho phép chỉnh sửa bất kỳ ô nào
                return false;
            }
        };
        modelTable.addColumn("Mã Loại Món");
        modelTable.addColumn("Tên Loại Món");
        
        ArrayList<LoaiMonDTO> list = loaiMonBUS.getAll();
        if (!list.isEmpty()) { // Kiểm tra danh sách không rỗng
            list.remove(0); // Xóa phần tử đầu tiên
        }
        for(int i = 0; i < list.size(); i++) {
            modelTable.addRow(new Object[] {
                list.get(i).getMaLoaiMon(),
                list.get(i).getTenLoaiMon(),
            });
        }
        tb_dsLoaiMon.setModel(modelTable);
    }
    public void reloadData() {
        tf_MaLoaiMon.setText("");
        tf_TenLoaiMon.setText("");
        fillTable();
    }
    public void btn_ThemAction() {
        int confirm = JOptionPane.showConfirmDialog(null,"Bạn có muốn thêm loại món này?","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if (confirm == JOptionPane.YES_OPTION) {
                    String maLoaiMon = String.valueOf(tf_MaLoaiMon.getText());
                    String tenLoaiMon = String.valueOf(tf_TenLoaiMon.getText());
                    if(tenLoaiMon.length() == 0) {
                        JOptionPane.showMessageDialog(null, "Tên loại món không được để trống !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    if(tenLoaiMon.length() > 50) {
                        JOptionPane.showMessageDialog(null, "Tên loại món không được vượt quá 50 ký tự !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    if(tenLoaiMon.matches(regex)) {
                        JOptionPane.showMessageDialog(null, "Tên loại món không được chứa ký tự đặc biệt !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        return;
                    };
                    LoaiMonDTO loaiMon = new LoaiMonDTO(maLoaiMon, tenLoaiMon, true);
                    
                for (LoaiMonDTO a : loaiMonBUS.getAll()) {
                    if(loaiMon.getTenLoaiMon().toLowerCase().trim().equals(a.getTenLoaiMon().toLowerCase().trim())) {
                        JOptionPane.showMessageDialog(null, "Tên loại món đã tồn tại !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                    if(loaiMonBUS.addLoaiMon(loaiMon)){
                        JOptionPane.showMessageDialog(null, "Thêm loại món thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        reloadData();
                    }
                    else 
                        JOptionPane.showMessageDialog(null, "Thêm loại món thất bại !", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
    }
    public void btn_XoaAction() {
        int selectedRow = tb_dsLoaiMon.getSelectedRow();
                if (selectedRow != -1) {
                    int confirm = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa loại món này?","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if (confirm == JOptionPane.YES_OPTION) {
                        String ma = String.valueOf(tf_MaLoaiMon.getText());
                        if(loaiMonBUS.deleteLoaiMon(ma)) {
                            JOptionPane.showMessageDialog(null, "Xóa loại món thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            reloadData();
                        }
                        else 
                        JOptionPane.showMessageDialog(null, "Xóa loại món thất bại !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn 1 sản phẩm để xóa !", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
    }
    public void btn_SuaAction() {
        int selectedRow = tb_dsLoaiMon.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(null,"Bạn có muốn sửa loại món này?","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                String maLoaiMon = String.valueOf(tf_MaLoaiMon.getText());
                String tenLoaiMon = String.valueOf(tf_TenLoaiMon.getText());
                if(tenLoaiMon.length() > 50) {
                    JOptionPane.showMessageDialog(null, "Tên loại món không được vượt quá 50 ký tự !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                if(tenLoaiMon.matches(regex)) {
                    JOptionPane.showMessageDialog(null, "Tên loại món không được chứa ký tự đặc biệt !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    return;
                };
                
                LoaiMonDTO loaiMon = new LoaiMonDTO(maLoaiMon, tenLoaiMon, true);
                if(loaiMonBUS.updateLoaiMon(loaiMon)){
                    JOptionPane.showMessageDialog(null, "Sửa loại món thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    reloadData();
                }
                else 
                    JOptionPane.showMessageDialog(null, "Sửa loại món thất bại !", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
        }else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn 1 sản phẩm để sửa !", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void btn_XuatExcelAction() {
        String fileName = "listLoaiMon.xlsx";
                String filePath = "src\\EXCEL\\"+fileName;
                Workbook workbook = new XSSFWorkbook();
                Sheet sheet = workbook.createSheet("Sheet1");

                // Lấy mô hình dữ liệu từ JTable
                TableModel model = tb_dsLoaiMon.getModel();
                // Tạo hàng tiêu đề (header)
                Row headerRow = sheet.createRow(0);
                for (int col = 0; col < model.getColumnCount(); col++) {
                    Cell cell = headerRow.createCell(col);
                    cell.setCellValue(model.getColumnName(col));
                }

                // Ghi dữ liệu từ JTable vào tệp Excel
                for (int row = 0; row < model.getRowCount(); row++) {
                    Row excelRow = sheet.createRow(row + 1);
                    for (int col = 0; col < model.getColumnCount(); col++) {
                        Cell cell = excelRow.createCell(col);
                        cell.setCellValue(model.getValueAt(row, col).toString());
                    }
                }
                // Ghi workbook vào tệp và mở tệp sau khi lưu
                try (FileOutputStream outputStream = new FileOutputStream(filePath)) {
                    workbook.write(outputStream);
                    workbook.close();
                    System.out.println("Xuất file Excel thành công!");

                    // Mở tệp ngay sau khi lưu
                    File file = new File(filePath);
                    if (Desktop.isDesktopSupported()) {
                        Desktop.getDesktop().open(file);
                    } else {
                        System.out.println("Mở tệp không được hỗ trợ trên hệ thống này.");
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XuatExcel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_MaLoaiMon;
    private javax.swing.JLabel lb_TenLoaiMon;
    private javax.swing.JTable tb_dsLoaiMon;
    private javax.swing.JTextField tf_MaLoaiMon;
    private javax.swing.JTextField tf_TenLoaiMon;
    // End of variables declaration//GEN-END:variables
}
